### ISSUE TITLE
Auction bot enhancements

### ISSUE THREAD

**Issue by PopcornPaws** [agoraxyz/gold-rust#26]
## Description
Auctions with cycle intervals under an hour might suffer from slight delays in closing a cycle. This is because the auction bot iterates over each auction in the pool and queries their state to decide whether to close the cycle or not. Furthermore, it also sleeps 5 seconds between iterations. Thus, it's easy to see that with a large number of auctions, closing a cycle might take minutes which may be a deal breaker for time-sensitive auctions.

## Solution
We might increase performance by spinning up multiple threads for iterations and closing cycles. The other option is to expose the auction bot as a docker service that anyone can run for themselves. We should also add the option for the bot to only monitor a single auction to circumvent iterations and focus only on a single auction.

## Todo
- [x] add warning when auction pool is more than 80% full with auctions #33 
- [x] add "focus mode" where the bot is only monitoring a single auction #33 
- [x] send and confirm transaction should be just send transaction #33 
- [x] log level should come from the cli options instead of the env logger and the default value should be info #33 
- [x] ~~use multiple threads for iteration~~
- [x] publish auction bot as a cli tool
